version: '3'
services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

volumes:
  mongo_data:
